name = "raffle-system"
main = "src/index.ts"
compatibility_date = "2024-05-12"
account_id = "f363e618f4b8dc5f5a3b8cb169f3ddb7"

# HMAC_SECRET is set via `wrangler secret put HMAC_SECRET`

[[durable_objects.bindings]]
name = "RAFFLE_SESSION"
class_name = "RaffleSession"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RaffleSession"]

# Static assets
[assets]
directory = "./public"
binding = "ASSETS"
